---
version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-minor-patch:
        applies-to: "version-updates"
        patterns: ["*"]
        update-types: ["minor", "patch"]
      npm-security:
        applies-to: "security-updates"
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      worker-npm-minor-patch:
        applies-to: "version-updates"
        patterns: ["*"]
        update-types: ["minor", "patch"]
      worker-npm-security:
        applies-to: "security-updates"
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      actions-minor-patch:
        applies-to: "version-updates"
        patterns: ["*"]
        update-types: ["minor", "patch"]
      actions-security:
        applies-to: "security-updates"
        patterns: ["*"]
